### PR TITLE
Update full-consensus-node.mdx

### PR DESCRIPTION
**Pull request by LavyshAlexander**
Fixed command for getting persistent peers.

## Overview

Previous version of command for saving persistent peers had bug with removing all new liners from peers list, and as a result node configuration was getting that list in non-readable form:

original list ([from here](https://raw.githubusercontent.com/celestiaorg/networks/master/mocha-4/peers.txt)):

``` 
34499b1ac473fbb03894c883178ecc83f0d6eaf6@64.227.18.169:26656
43e9da043318a4ea0141259c17fcb06ecff816af@rpc-1.celestia.nodes.guru:43656
f9e950870eccdb40e2386896d7b6a7687a103c99@rpc-2.celestia.nodes.guru:43656
daf2cecee2bd7f1b3bf94839f993f807c6b15fbf@celestia-testnet-peer.itrocket.net:11656
```

original command:

```
PERSISTENT_PEERS=$(curl -sL https://raw.githubusercontent.com/celestiaorg/networks/master/mocha-4/peers.txt | tr -d '\n')
echo $PERSISTENT_PEERS
```

results in:

```
34499b1ac473fbb03894c883178ecc83f0d6eaf6@64.227.18.169:2665643e9da043318a4ea0141259c17fcb06ecff816af@rpc-1.celestia.nodes.guru:43656f9e950870eccdb40e2386896d7b6a7687a103c99@rpc-2.celestia.nodes.guru:43656daf2cecee2bd7f1b3bf94839f993f807c6b15fbf@celestia-testnet-peer.itrocket.net:11656
```

new command:

```
PERSISTENT_PEERS=$(curl -sL https://raw.githubusercontent.com/celestiaorg/networks/master/mocha-4/peers.txt | head -c -1 | tr '\n' ',')
```

results in:

```
34499b1ac473fbb03894c883178ecc83f0d6eaf6@64.227.18.169:26656,43e9da043318a4ea0141259c17fcb06ecff816af@rpc-1.celestia.nodes.guru:43656,f9e950870eccdb40e2386896d7b6a7687a103c99@rpc-2.celestia.nodes.guru:43656,daf2cecee2bd7f1b3bf94839f993f807c6b15fbf@celestia-testnet-peer.itrocket.net:11656
```

## Known issues ##

Mac users built-in `head` command does not except negative numbers for `-c` flag.
Solution is to install `coreutils` package and use `ghead` command from it.

```
brew install coreutils
```

and optionally set alias from `head` to `ghead` in shell config (`~/.bashrc`, `~/.zshrc` etc):

```
alias head=ghead
```

## Checklist

- [+] New and updated code has appropriate documentation
- [+] New and updated code has new and/or updated testing
- [+] Required CI checks are passing
- [+] Visual proof for any user facing features like CLI or documentation updates
- [+] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
linking this issue, as different formatting in networks repo is causing issues: https://github.com/celestiaorg/networks/issues/350

**Comment by jcstein** [comment]
thanks for the PR @LavyshAlexander - could you please add the instructions for mac users within the page?

**Comment by LavyshAlexander** [comment]
yeah, of course, @jcstein. Now instruction with note for mac users ;)

**Comment by jcstein** [comment]
thanks @LavyshAlexander! I think that we should add to the arabica instructions as well, as the [formatting of that peers file is the same](https://github.com/celestiaorg/networks/blob/master/arabica-10/peers.txt)

**Comment by LavyshAlexander** [comment]
Updated instruction for arabica and some additional formattings.

**Review by jcstein — APPROVED** [review]
LGTM! :shipit: thanks again @LavyshAlexander for this PR!

**Pull request merged**
