### PR TITLE
remove persistent peers

### PR DESCRIPTION
**Pull request by rooiie**
remove persistent peers from the manual.

### CODE REVIEW

**Review by evan-forbes — COMMENTED** [review]
just to triple check, starting a node using this guide still works I'm guessing?

**Comment by yelllowsin** [comment]
@rooiie I think Rooie has been guiding users to do so yeh. But will let him confirm first.

**Comment by YazzyYaz** [comment]
just confirmed it works for me @yelllowsin @evan-forbes @adlerjohn as I was stuck on syncing a validator node with persistent-peers being populated with peers.

**Review by evan-forbes — APPROVED** [review]
utACK :+1:

**Review by adlerjohn — APPROVED** [review]
yaztACK

**Pull request merged**
