### PR TITLE
docs: update quick-sync

### PR DESCRIPTION
**Pull request by qubelabsio**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

## Summary by CodeRabbit

- **Refactor**
	- Updated the method for downloading and extracting snapshots in the consensus node documentation to use `aria2c`, enhancing the efficiency of the process.
- **Documentation**
	- Added `aria2` to the list of packages installed via `apt` and `yum` commands in the environment setup documentation.

### CODE REVIEW

**Review by jcstein — CHANGES_REQUESTED** [review]
- [ ] update other instances of wget
- [ ] replace wget with aria2c as a dependency in environment setup

**Comment by qubelabsio** [comment]
> * [ ]  update other instances of wget
> * [ ]  replace wget with aria2c as a dependency in environment setup

@jcstein I wouldn't update other instances of wget, as it remains the preferred method for validators. However, for snapshots, which are optional but large in size, it makes sense to use `aria2` instead.

I added `aria2` to dependencies but left `wget` also, if that is ok?

**Review by jcstein — APPROVED** [review]

**Review by jcstein — APPROVED** [review]

**Comment by jcstein** [comment]
i just realized this doesn't work for mac now unless i just can't find the right way to install aria2c?

**Comment by jcstein** [comment]
nvm `brew install aria2`

**Pull request merged**
