### PR TITLE
Update install commands for Ubuntu(AMD)

### PR DESCRIPTION
**Pull request by ZacharyHRQ**
faced some problems installing the node, fix it by adding "make build"

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
thanks for the PR. if we add this revision, will need to make changes wherever AMD instructions appear across docs

**Comment by jcstein** [comment]
hi again @ZacharyHRQ! could you please elaborate on what errors you saw when running `make install`? thanks!

**Comment by ZacharyHRQ** [comment]
the build file could not be found

**Comment by jcstein** [comment]
made a small change and adding across the docs. thanks again for the PR @ZacharyHRQ!

**Review by jcstein — APPROVED** [review]
:shipit:

**Pull request merged**
