### PR TITLE
Add WebSocket endpoints Cumulo

### PR DESCRIPTION
**Pull request by santosdios**
## Summary by CodeRabbit

- **New Features**
	- Updated documentation for Celestia’s Mainnet Beta, detailing network stability, upgrades, and parameters.
	- Expanded information on transaction limits and block size calculations.
	- Added a comprehensive list of production RPC endpoints and community consensus nodes.
	- Enhanced resources for monitoring network activity and performance.

- **Documentation**
	- Included links for users to stay updated on network upgrades via Telegram and Discord.

### CODE REVIEW

**Review by jcstein — APPROVED** [review]

**Comment by jcstein** [comment]
not sure how to merge this because auto-merge is only option cc @MSevey ? but this won't work because it's waiting on PR previews to deploy

**Comment by jcstein** [comment]
gm @santosdios can you pull in latest main?

**Comment by santosdios** [comment]
I hope it will be OK some days I hate GitHub :-)

**Comment by jcstein** [comment]
same lol!!

**Pull request merged**
