### PR TITLE
docs[fix] - localhost -> 0.0.0.0

### PR DESCRIPTION
**Pull request by samlaf**
On my mac, localhost resulting in error:
```
Error: gateway: invalid listen address format: localhost
```

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
thank you! this is a known bug and will be fixed in an upcoming release

**Comment by adlerjohn** [comment]
@jcstein should this be merged then reverted, or just held off until the release? If the release is more than a bit away, IMO it would be better to merge so that at least the docs are correct.

**Comment by jcstein** [comment]
good cal @adlerjohn. @distractedm1nd will this be updated for Mocha?

**Review by jcstein — COMMENTED** [review]
thank you again @samlaf - could you add the changes that are in this branch please? then I will merge. https://github.com/celestiaorg/docs/commit/757f21108c69e4e434d261735b1c74743caa5067

**Comment by samlaf** [comment]
Done

**Review by jcstein — APPROVED** [review]
Looks good to me. Thanks again!

**Pull request merged**
