### PR TITLE
Add Gem Wallet

### PR DESCRIPTION
**Pull request by gememerald8**
## Overview

Add Gem Wallet for Celestia Staking guide.

## Summary by CodeRabbit

- **Documentation**
  - Expanded the tutorial on how to stake TIA to include detailed instructions for staking with the Gem wallet, in addition to Keplr and Leap wallets.

### CODE REVIEW

**Comment by jcstein** [comment]
is gem open source?

**Comment by gemcoder21** [comment]
> is gem open source?

Yes, just recently open sourced it, finally all the parts now are open source:
1) Core: https://github.com/gemwalletcom/core
2) iOS App: https://github.com/gemwalletcom/gem-ios
3) Android: https://github.com/gemwalletcom/gem-android

**Comment by jcstein** [comment]
are there any audits available @gemcoder21 ?

**Comment by gemcoder21** [comment]
> are there any audits available @gemcoder21 ?

Gem Wallet core is build on top of [Wallet Core](https://github.com/trustwallet/wallet-core/tree/master/audit) (link to the audit) which has been audited. We do plan to audit our own codebase in the next as well as having reproducible builds, It's on our [Gem Wallet Roadmap](https://github.com/orgs/gemwalletcom/projects/4/views/1) as we build in public for the public. 

Feel free to take a look at our [Security](https://gemwallet.com/security/) page to learn how Gem Wallet handles Security and Privacy.

**Comment by jcstein** [comment]
thank you @gemcoder21 !

**Review by jcstein — APPROVED** [review]

**Pull request merged**
