### PR TITLE
Added MMS team endpoints for mocha-3

### PR DESCRIPTION
**Pull request by nochanc3**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
have these been tested with the UX that is in the docs for starting a node?

please provide logs. thank you

**Comment by nochanc3** [comment]
> have these been tested with the UX that is in the docs for starting a node?
> 
> please provide logs. thank you

Hey, we have no problem testing, can you give me a link to what you mean ?

**Comment by jcstein** [comment]
totally! just something like starting a light node against the endpoint and using it to submit a tx: https://docs.celestia.org/nodes/light-node/#start-the-light-node

**Review by jcstein — APPROVED** [review]

**Comment by nochanc3** [comment]
> totally! just something like starting a light node against the endpoint and using it to submit a tx: https://docs.celestia.org/nodes/light-node/#start-the-light-node

Oh yeah, no problem, I'll get the results to you shortly.

**Review by jcstein — APPROVED** [review]

**Comment by jcstein** [comment]
worked for me! good to go 🫡 https://app.warp.dev/block/LPWB6jBWr3kcwXs75eNoqc thank you for the PR.

**Comment by jcstein** [comment]
the error in the build is from a bad link i merged in. can you please change the existing version of [this endpoint on the page](https://github.com/mms-team/docs/blob/1dc1e37dee88e8f792e0a4b7065d32121a95494b/docs/nodes/mocha-testnet.mdx#L89) to:

"* `celestia-testnet-grpc.itrocket.net:11090`" 

so, remove it from being a link and just format it as code with no http/https? thanks! i tried to push to your branch but wasn't able

**Comment by jcstein** [comment]
sorry, could you please resolve conflicts?

and while you are, to avoid a build error with a bad link [here](https://github.com/mms-team/docs/blob/1dc1e37dee88e8f792e0a4b7065d32121a95494b/docs/nodes/mocha-testnet.mdx#L89)

it can be changed to:
"* celestia-testnet-grpc.itrocket.net:11090"

**Comment by nochanc3** [comment]
> sorry, could you please resolve conflicts?
> 
> and while you are, to avoid a build error with a bad link [here](https://github.com/mms-team/docs/blob/1dc1e37dee88e8f792e0a4b7065d32121a95494b/docs/nodes/mocha-testnet.mdx#L89)
> 
> it can be changed to: "* `celestia-testnet-grpc.itrocket.net:11090`"
Hey, sorry for the delay
I've updated the PR
you can find the logs here: 
https://github.com/mms-team/logs/blob/main/Light%20node%20logs

**Pull request merged**
