### PR TITLE
Sentence case titles

### PR DESCRIPTION
**Pull request by rootulp**
I preserved capitalization for H1s where the noun was the sidebar name (ex. `Full Storage Node`, `Bridge Node`, etc.) and sentence cased all other titles (H2+).

Resolves https://github.com/celestiaorg/docs/issues/161

### CODE REVIEW

**Comment by YazzyYaz** [comment]
Hey @rootulp I'll get back to this next week, my general thinking though is that title case are fine in sub-headings as they're still titles. 

What is the thinking around lower-casing subheadings below H1? Is that part of a style guide you can link me to?

**Comment by rootulp** [comment]
No rush on reviewing this, next week is fine. We should align on whether we want https://github.com/celestiaorg/docs/issues/161

> What is the thinking around lower-casing subheadings below H1? Is that part of a style guide you can link me to?

It's a style thing. https://design-system.service.gov.uk/styles/typography/#headings states:

> Write all headings in sentence case.

but I'm sure we can find style guides that state the opposite. This PR was motivated by me noticing that the docs contain a lot of capitalization (in titles and paragraphs) which led to my confusion on which words were proper nouns. We probably don't _need_ sentence-cased titles if we do https://github.com/celestiaorg/docs/issues/160 along with downcasing words in paragraphs that aren't proper nouns.

**Comment by YazzyYaz** [comment]
I can go either way, although not too sure on the new styling.

@dabit3 any thoughts?

**Comment by rootulp** [comment]
> I.e. are Light / Bridge / Full / etc... nodes a proper noun? Or is it just at type of Celestia node?

I think just a type of node. For example "light client" and "light node" are not capitalized in:
- https://ethereum.org/en/developers/tutorials/run-light-node-geth/
- https://geth.ethereum.org/docs/interface/les

**Comment by dabit3** [comment]
@rootulp makes sense, looks great to me!

**Review by adlerjohn — APPROVED** [review]

**Comment by rootulp** [comment]
I have a lot of other fixes I'd like to make to these docs queued up after this merges

**Pull request merged**
