### PR TITLE
fix celestia node install for mac(apple)

### PR DESCRIPTION
**Pull request by gupadhyaya**
While i was trying to build celestia node on mac (apple), ran into a couple of issues in the doc such as:
* the `go-install` target does not exist in the Makefile, hence changing to `make install`
* hit an error while running `make install`
```
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
```
* for which, i had to update keyring from v1.1.6 v1.2.1 in the go.mod file and 
* run `go get github.com/cosmos/cosmos-sdk/crypto/keyring@v0.46.0-beta2.0.20220418184507-c53157dd63f6`

### CODE REVIEW

**Comment by jcstein** [comment]
thank you for this @gupadhyaya - I'll take a look later today or tomorrow and test this out

**Comment by jcstein** [comment]
although `make go-install` isn't in the makefile, it still seems to work fine for me, but shows a different error during installation

```jcs @ ~/celestia-node % make go-install


--> Installing Celestia
# github.com/rjeczalik/notify
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
jcs @ ~/celestia-node % celestia

		____      __          __  _
	  / ____/__  / /__  _____/ /_(_)___ _
	 / /   / _ \/ / _ \/ ___/ __/ / __  /
	/ /___/  __/ /  __(__  ) /_/ / /_/ /
	\____/\___/_/\___/____/\__/_/\__,_/

Usage:
  celestia [command]

Available Commands:
  bridge      Manage your Bridge node
  full        Manage your Full node
  light       Manage your Light node
  version     Show information about the current binary build

Flags:
  -h, --help   help for celestia

Additional help topics:
  celestia

Use "celestia [command] --help" for more information about a command.
jcs @ ~/celestia-node % celestia version
Semantic version: v0.4.2
Commit: 75b122f736d0db758ef840a4bf3b2e6635e823bd
Build Date: Wed Nov  9 15:23:07 EST 2022
System version: arm64/darwin
Golang version: go1.19.1
```

i'm wiping this version and testing out with `make install`

**Comment by jcstein** [comment]
which network were you installing for @gupadhyaya?

**Comment by jcstein** [comment]
adding comments here relevant to this PR

### Re: `make go-install`
@gupadhyaya was installing for Mamaki, and there is no `go-install` in the Makefile for v0.3.0-rc2
there is `go-install` [in makefile](https://github.com/celestiaorg/celestia-node/blob/v0.4.2/Makefile#L51) for v0.4.0

### Re: [error above](https://github.com/celestiaorg/docs/pull/300#:~:text=install%3A%20/usr/local/bin//celestia%3A%20Permission%20denied)
`install: /usr/local/bin//celestia: Permission denied`
is just a permission issue. if you `sudo make install` or change the bin directory to `~/go/bin` it should go away

**Comment by jcstein** [comment]
verifying that `make install` works for `celestia-node v0.3.0-rc2` and that `make go-install` works for `celestia-node v0.4.2`

**Comment by jcstein** [comment]
- [x] added error workaround in all Mamaki Mac installation commands
- [x] reverted to `make go-install` for Arabica (celestia-node v0.4.2)
- [x] changed Mamaki installation command to `make install` (celestia-node v0.3.0-rc2)

**Comment by jcstein** [comment]
@MSevey I believe the Deploy PR Preview is [failing](https://github.com/celestiaorg/docs/actions/runs/3447766794/jobs/5754120396#step:6:202) due to this being a branch off of main

**Comment by YazzyYaz** [comment]
Maybe it's failing due to permissions? That members who can display PR Previews need to be official contributors to this repo? I've seen it fail for external contributors. It's not a requirement that it needs to pass for us to merge this btw.

**Comment by YazzyYaz** [comment]
I'll build it locally later to see how the changes render

**Review by jcstein — APPROVED** [review]
- [x] changing commands for mamaki
- [x] left off error resolution, update of node/app is imminent

**Review by jcstein — APPROVED** [review]

**Comment by MSevey** [comment]
> @YazzyYaz / @MSevey I believe the Deploy PR Preview is [failing](https://github.com/celestiaorg/docs/actions/runs/3447766794/jobs/5754120396#step:6:202) due to this being a branch off of main. is that what it is?

sorry, lost track of this

I believe @YazzyYaz is correct. The action might have some permission issues with forks depending on the user's permissions. 

But it isn't blocking, mostly a helper.

**Pull request merged**
