### PR TITLE
update blob module examples on node-tutorial to match upcoming RC

### LINKED ISSUE #929: update RPC CLI / node-tutorial page for breaking changes
https://github.com/celestiaorg/celestia-node/pull/2521#issuecomment-1665433931

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Resolves #929, making [updates](https://github.com/celestiaorg/celestia-node/pull/2521#issuecomment-1665433931) to the `blob` module.

This may have more changes, depending on when other modules are made to match kebab-case ([context](https://github.com/celestiaorg/celestia-node/pull/2521#issuecomment-1667884136)).

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by renaynay** [comment]
@jcstein just FYI the upcoming RC will not be deployed on either arabica or mocha for now (so just wait to merge this til then)

**Comment by jcstein** [comment]
- [ ] add note about custom/private network flag needing a --node.store flag to point to a different network, as a security precaution

**Comment by jcstein** [comment]
moving to site with "next" version as this is the "next" version

**Comment by jcstein** [comment]
#985

**Pull request closed without merging**
