### PR TITLE
Update systemd.md

### PR DESCRIPTION
**Pull request by cryptomolot**
## Modify the bridge node guide 

Changing LimitNOFILE number according to https://github.com/celestiaorg/docs/issues/1633

## Summary by CodeRabbit

- **Bug Fixes**
  - Adjusted the `LimitNOFILE` value in system configuration from `1400000` to `65535` to ensure compatibility and stability.
  - Added a note advising users on the implications of setting high file descriptor limits for system performance.

### CODE REVIEW

**Comment by jcstein** [comment]
cc @jbowen93

**Comment by jcstein** [comment]
reverts https://github.com/celestiaorg/docs/pull/1407

**Comment by jcstein** [comment]
@cryptomolot do you want to also change the other instances of 140000?

**Comment by cryptomolot** [comment]
> @cryptomolot do you want to also change the other instances of 140000?

Sure! Sorry for late response 

Will do

**Comment by jcstein** [comment]
nbd! thanks @cryptomolot

**Comment by jcstein** [comment]
cc @Wondertan and @renaynay for review here please 🙏

**Pull request closed without merging**
