### PR TITLE
Adding Spidey Mocha-4 RPC, gRPC and API public endpoints

### PR DESCRIPTION
**Pull request by spidey-169**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
hmm, i see no changes?

**Comment by jcstein** [comment]
@spidey-169

**Comment by jcstein** [comment]
please reopen when you find this 😄 @spidey-169

**Comment by spidey-169** [comment]
@jcstein Sorry just saw your message.  https://github.com/celestiaorg/docs/pull/1307/commits/70b6466de83c4b2bb188a434d7f1d3430b222e13
 was the previous commit where I had added rpc,grpc and API endpoints and had opened a PR for this. I am trying to open another PR for this with this change again

**Comment by spidey-169** [comment]
Created a fresh PR https://github.com/celestiaorg/docs/pull/1335. Thanks @jcstein

**Comment by jcstein** [comment]
you're welcome! will review #1335

**Pull request closed without merging**
