### PR TITLE
Add trailing slash to all internal links

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Closes https://github.com/celestiaorg/docs/issues/425

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by musalbas** [comment]
Do we also need to add it to the sidebars?

**Comment by jcstein** [comment]
yes, good catch

**Comment by musalbas** [comment]
Does that mean the sidebar links don't have trailing slashes -- is there another way to make them do so?

**Comment by homotechsual** [comment]
> Does that mean the sidebar links don't have trailing slashes -- is there another way to make them do so?

 They aren't supposed to have trailing slashes, they aren't URLs or paths - they are doc ids. If the resulting sidebar links don't have trailing slashes look at your trailing slash config.

**Comment by jcstein** [comment]
How could I modify the trailing slash config correctly to add trailing slashes? Thanks for tagging in @homotechsual

**Comment by homotechsual** [comment]
https://docusaurus.io/docs/api/docusaurus-config#trailingSlash = true means your environment should have trailing slashes so Docusaurus will make links with them.

**Comment by jcstein** [comment]
Looks like this works! URL copied from sidebar in local dev looks like: `http://localhost:3000/developers/overview/`

**Comment by musalbas** [comment]
If enabling that option worked, does that mean we also don't need to manually add the trailing slashes in the other places outside of the sidebar (as in the original PR)?

**Comment by homotechsual** [comment]
It will depend on the specific links - if you're doing URL links `/thing/thing/thing` then yes - trailing `/` is on you.

If you're doing MD/MDX links (recommended where possible!) `../../category/subcategory/doc.md` then no - Docusaurus handles it.

**Comment by musalbas** [comment]
>If you're doing MD/MDX links (recommended where possible!) ../../category/subcategory/doc.md then no - Docusaurus handles it.

Sounds like we can do a bunch of the original changes in that case @jcstein.

**Comment by jcstein** [comment]
it didn't work as I expected after action ran (https://github.com/celestiaorg/docs/actions/runs/3990557457/jobs/6844342152#step:5:30). will remove the original changes and test out new trailingSlash config

**Comment by jcstein** [comment]
it worked on [Rollkit](https://github.com/rollkit/docs/commit/3220b4615b4a0761464b1ef98d0200df721be3ba). so will make same change on Celestia docs

**Comment by jcstein** [comment]
I have added .md/.mdx to all relative links on Celestia docs in this PR. I have not used absolute links in this PR and will revert the ones in the commit I shared above from Rollkit to use relative links

For example, the "Core Concepts" section callout at the top links to tutorials (https://rollkit.dev/docs/category/tutorials/) which has a trailing slash and is written as: `Rollkit [does not yet support fraud proofs](./rollkit-stack.md).`

**Comment by jcstein** [comment]
I have added .md/.mdx to all relative links on Celestia docs in this PR. I have not used absolute links in this PR and will revert the ones in the commit I shared above from Rollkit to use relative links

For example, the "Core Concepts" section callout in the Fraud Proofs section links to `./rollkit-stack.md` (`https://rollkit.dev/docs/rollkit-stack/`) which has a trailing slash and is written as: Rollkit [does not yet support fraud proofs](./rollkit-stack.md).

**Review by YazzyYaz — APPROVED** [review]

**Pull request merged**
